services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stops_gg_app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - docker_manga_network
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.stopsgg.rule=Host(`${DOMAIN:-stops.gg}`)'
      - 'traefik.http.routers.stopsgg.entrypoints=websecure'
      - 'traefik.http.routers.stopsgg.tls=true'
      - 'traefik.http.routers.stopsgg.tls.certresolver=letsencrypt'
      - 'traefik.http.services.stopsgg.loadbalancer.server.port=80'

networks:
  docker_manga_network:
    external: true
